// paisaads-angular/src/app/pages/search/search.component.ts
import { Component, inject, signal, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { ApiService } from '../../shared/services/api.service';
import { CategoryTree, SearchSlogan } from '../../shared/models/models';

@Component({
  selector: 'app-search',
  standalone: true,
  template: `
    <div class="pt-20 flex flex-col items-center justify-center px-4">
      <div class="text-center max-w-4xl mx-auto">
        <h1 class="text-4xl md:text-6xl font-bold text-gray-900 mb-8">{{ sloganData()?.primarySlogan || 'Find What You Need' }}</h1>
        <p class="text-lg md:text-xl text-gray-600 mb-12">{{ sloganData()?.secondarySlogan || 'Search through thousands of classified advertisements' }}</p>
        <div class="bg-white rounded-lg p-6 shadow-sm border border-gray-200 max-w-5xl mx-auto">
          <form (ngSubmit)="onSubmit()" class="space-y-4">
            <div class="grid grid-cols-1 md:grid-cols-5 gap-3 items-end">
              <select [(ngModel)]="categoryId" name="categoryId" class="h-10 w-full rounded-md border border-gray-300 bg-white px-3 py-2 text-sm">
                <option value="">Select category</option>
                @for (cat of flatCategories(); track cat.id) {
                  <option [value]="cat.id">{{ cat.name }}</option>
                }
              </select>
              <input type="text" [(ngModel)]="stateName" name="state" placeholder="Select State" class="h-10 w-full rounded-md border border-gray-300 bg-white px-3 py-2 text-sm" />
              <input type="text" [(ngModel)]="cityName" name="city" placeholder="Select City" class="h-10 w-full rounded-md border border-gray-300 bg-white px-3 py-2 text-sm" />
              <input type="text" [(ngModel)]="countryName" name="country" placeholder="Select Country" class="h-10 w-full rounded-md border border-gray-300 bg-white px-3 py-2 text-sm" />
              <button type="submit" class="h-10 px-6 bg-[#1a1a2e] text-white rounded-md">
                <svg class="mr-2 h-4 w-4 inline" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"/></svg>
                Search
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  `,
  imports: [FormsModule],
})
export class SearchComponent implements OnInit {
  private api = inject(ApiService);
  private router = inject(Router);
  categories = signal<CategoryTree[]>([]);
  flatCategories = signal<{id: string; name: string}[]>([]);
  sloganData = signal<SearchSlogan | null>(null);
  categoryId = '';
  stateName = '';
  cityName = '';
  countryName = '';

  ngOnInit() {
    this.api.getCategoryTree().subscribe(data => {
      this.categories.set(data);
      this.flatCategories.set(this.api.flattenCategories(data));
    });
    this.api.getSearchSlogan().subscribe(data => this.sloganData.set(data));
  }

  onSubmit() {
    const params = new URLSearchParams();
    if (this.categoryId) params.append('categoryId', this.categoryId);
    if (this.stateName) params.append('state', this.stateName);
    if (this.cityName) params.append('city', this.cityName);
    this.router.navigate(['/search/results'], { queryParams: { categoryId: this.categoryId || undefined, state: this.stateName || undefined, city: this.cityName || undefined } });
  }
}

// frontend/src/app/(website)/search/page.tsx
import Link from "next/link";

const API_BASE = process.env.NEXT_PUBLIC_API_URL || "https://vhlafnxhkalzwzlcbidq.supabase.co/functions/v1/paisaads-api";

async function fetchCategories() {
  try {
    const res = await fetch(`${API_BASE}/categories/tree`, { next: { revalidate: 300 } });
    if (!res.ok) return [];
    return await res.json();
  } catch {
    return [];
  }
}

async function fetchSlogan() {
  try {
    const res = await fetch(`${API_BASE}/configurations/search-slogan`, { next: { revalidate: 300 } });
    if (!res.ok) return { primarySlogan: "Find What You Need", secondarySlogan: "Search through thousands of classified advertisements" };
    return await res.json();
  } catch {
    return { primarySlogan: "Find What You Need", secondarySlogan: "Search through thousands of classified advertisements" };
  }
}

function flattenCategories(categories: any[]): any[] {
  let result: any[] = [];
  categories.forEach((category) => {
    result.push({ id: category.id, name: category.name });
    if (category.children && category.children.length > 0) {
      result = [...result, ...flattenCategories(category.children)];
    }
  });
  return result;
}

export default async function SearchPage() {
  const [categories, sloganData] = await Promise.all([
    fetchCategories(),
    fetchSlogan(),
  ]);

  const flatCategories = flattenCategories(categories);

  return (
    <div className="pt-20 flex flex-col items-center justify-center px-4">
      <div className="text-center max-w-4xl mx-auto">
        <h1 className="text-4xl md:text-6xl font-bold text-gray-900 mb-8">
          {sloganData.primarySlogan || "Find What You Need"}
        </h1>

        <p className="text-lg md:text-xl text-gray-600 mb-12">
          {sloganData.secondarySlogan || "Search through thousands of classified advertisements"}
        </p>

        <div className="bg-white rounded-lg p-6 shadow-sm border border-gray-200 max-w-5xl mx-auto">
          <form action="/search/results" className="space-y-4">
            <div className="grid grid-cols-1 md:grid-cols-4 gap-3 items-end">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Category</label>
                <select
                  name="categoryId"
                  className="h-10 w-full rounded-md border border-gray-300 bg-white px-3 py-2 text-sm"
                >
                  <option value="">All Categories</option>
                  {flatCategories.map((category) => (
                    <option key={category.id} value={category.id}>
                      {category.name}
                    </option>
                  ))}
                </select>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">State</label>
                <input
                  type="text"
                  name="state"
                  placeholder="Enter state"
                  className="h-10 w-full rounded-md border border-gray-300 bg-white px-3 py-2 text-sm"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">City</label>
                <input
                  type="text"
                  name="city"
                  placeholder="Enter city"
                  className="h-10 w-full rounded-md border border-gray-300 bg-white px-3 py-2 text-sm"
                />
              </div>

              <button
                type="submit"
                className="h-10 px-6 bg-blue-600 hover:bg-blue-700 text-white rounded-md text-sm font-medium transition-colors"
              >
                Search
              </button>
            </div>
          </form>
        </div>

        <div className="mt-8 flex flex-wrap justify-center gap-2">
          {categories.map((cat: any) => (
            <Link
              key={cat.id}
              href={`/search/results?search=${encodeURIComponent(cat.name)}`}
              className="rounded-full bg-slate-100 px-4 py-2 text-sm font-medium text-slate-700 hover:bg-slate-200 transition-colors"
            >
              {cat.name}
            </Link>
          ))}
        </div>
      </div>
    </div>
  );
}
