// frontend/src/app/mgmt/dashboard/configurations/search-slogan/page.tsx
"use client";

import { useState, useEffect } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Skeleton } from "@/components/ui/skeleton";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Search, Save, Eye, AlertCircle, Type } from "lucide-react";
import { toast } from "sonner";
import { format } from "date-fns";
import api from "@/lib/api";

interface SearchSlogan {
  _id?: string;
  primarySlogan: string;
  secondarySlogan?: string;
  isActive: boolean;
  lastUpdated: Date;
  updatedBy: string;
}

interface SearchSloganForm {
  primarySlogan: string;
  secondarySlogan: string;
}

export default function SearchSloganConfig() {
  const [formData, setFormData] = useState<SearchSloganForm>({
    primarySlogan: "",
    secondarySlogan: ""
  });
  const [hasChanges, setHasChanges] = useState(false);
  const [showPreview, setShowPreview] = useState(false);

  const queryClient = useQueryClient();

  const { data: currentSlogan, isLoading, error } = useQuery({
    queryKey: ["search-slogan"],
    queryFn: async () => {
      const { data } = await api.get("/configurations/search-slogan");
      return data as SearchSlogan;
    }
  });

  const updateSloganMutation = useMutation({
    mutationFn: async (sloganData: SearchSloganForm) => {
      const { data } = await api.post("/configurations/search-slogan", sloganData);
      return data;
    },
    onSuccess: () => {
      toast.success("Search slogan updated successfully");
      queryClient.invalidateQueries({ queryKey: ["search-slogan"] });
      setHasChanges(false);
    },
    onError: (error: any) => {
      toast.error(error.response?.data?.message || "Failed to update search slogan");
    }
  });

  useEffect(() => {
    if (currentSlogan) {
      setFormData({
        primarySlogan: currentSlogan.primarySlogan,
        secondarySlogan: currentSlogan.secondarySlogan || ""
      });
      setHasChanges(false);
    }
  }, [currentSlogan]);

  const handleFormChange = (field: keyof SearchSloganForm, value: string) => {
    setFormData(prev => ({ ...prev, [field]: value }));
    setHasChanges(true);
  };

  const handleSave = () => {
    updateSloganMutation.mutate(formData);
  };

  if (error) {
    return (
      <Alert variant="destructive">
        <AlertCircle className="h-4 w-4" />
        <AlertDescription>
          Failed to load search slogan configuration. Please try again.
        </AlertDescription>
      </Alert>
    );
  }

  return (
    <div className="space-y-6">
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Search className="h-5 w-5" />
            Search Page Slogan Configuration
          </CardTitle>
        </CardHeader>
        <CardContent>
          {isLoading ? (
            <div className="space-y-4">
              <Skeleton className="h-10" />
              <Skeleton className="h-20" />
              <Skeleton className="h-10 w-32" />
            </div>
          ) : (
            <div className="space-y-6">
              {currentSlogan && (
                <div className="bg-gradient-to-r from-blue-50 to-indigo-50 border border-blue-200 rounded-lg p-6">
                  <div className="text-center space-y-2">
                    <h2 className="text-2xl font-bold text-blue-900">
                      {currentSlogan.primarySlogan}
                    </h2>
                    {currentSlogan.secondarySlogan && (
                      <p className="text-blue-700 text-lg">
                        {currentSlogan.secondarySlogan}
                      </p>
                    )}
                    <Badge variant="secondary" className="mt-2">
                      Current Active Slogan
                    </Badge>
                  </div>
                </div>
              )}

              <div className="space-y-4">
                <div className="space-y-2">
                  <Label htmlFor="primarySlogan" className="flex items-center gap-2">
                    <Type className="h-4 w-4" />
                    Primary Slogan
                  </Label>
                  <Input
                    id="primarySlogan"
                    value={formData.primarySlogan}
                    onChange={(e) => handleFormChange("primarySlogan", e.target.value)}
                    placeholder="Enter primary slogan (e.g., 'Find Your Perfect Ad Solution')"
                    maxLength={100}
                  />
                  <div className="text-xs text-muted-foreground">
                    {formData.primarySlogan.length}/100 characters
                  </div>
                </div>

                <div className="space-y-2">
                  <Label htmlFor="secondarySlogan">
                    Secondary Slogan (Optional)
                  </Label>
                  <Textarea
                    id="secondarySlogan"
                    value={formData.secondarySlogan}
                    onChange={(e) => handleFormChange("secondarySlogan", e.target.value)}
                    placeholder="Enter secondary slogan for additional context (e.g., 'Browse thousands of verified listings')"
                    maxLength={200}
                    rows={3}
                  />
                  <div className="text-xs text-muted-foreground">
                    {formData.secondarySlogan.length}/200 characters
                  </div>
                </div>
              </div>

              {showPreview && (
                <div className="space-y-2">
                  <Label>Preview</Label>
                  <div className="bg-gradient-to-r from-gray-50 to-gray-100 border rounded-lg p-6">
                    <div className="text-center space-y-2">
                      <h2 className="text-2xl font-bold text-gray-900">
                        {formData.primarySlogan || "Your Primary Slogan"}
                      </h2>
                      {formData.secondarySlogan && (
                        <p className="text-gray-700 text-lg">
                          {formData.secondarySlogan}
                        </p>
                      )}
                    </div>
                  </div>
                </div>
              )}

              <div className="flex justify-between items-center">
                <Button
                  variant="outline"
                  onClick={() => setShowPreview(!showPreview)}
                  className="flex items-center gap-2"
                >
                  <Eye className="h-4 w-4" />
                  {showPreview ? "Hide" : "Show"} Preview
                </Button>
                <div className="flex items-center gap-2">
                  {hasChanges && (
                    <span className="text-sm text-muted-foreground">
                      Unsaved changes
                    </span>
                  )}
                  <Button
                    onClick={handleSave}
                    disabled={!hasChanges || updateSloganMutation.isPending || !formData.primarySlogan.trim()}
                    className="flex items-center gap-2"
                  >
                    <Save className="h-4 w-4" />
                    {updateSloganMutation.isPending ? "Saving..." : "Save Changes"}
                  </Button>
                </div>
              </div>

              {currentSlogan && (
                <div className="text-sm text-muted-foreground border-t pt-4">
                  <div className="flex items-center justify-between">
                    <span>
                      Last updated: {format(new Date(currentSlogan.lastUpdated), "PPpp")}
                    </span>
                    <span>
                      Updated by: {currentSlogan.updatedBy}
                    </span>
                  </div>
                </div>
              )}
            </div>
          )}
        </CardContent>
      </Card>

    </div>
  );
}

// paisaads-angular/src/app/pages/admin/configurations/search-slogan/search-slogan.component.ts
import { Component, inject, signal, OnInit } from '@angular/core';
import { ReactiveFormsModule, FormGroup, FormControl, Validators } from '@angular/forms';
import { DatePipe } from '@angular/common';
import { ApiService } from '../../../../shared/services/api.service';
import { NotificationService } from '../../../../shared/services/notification.service';

@Component({
  selector: 'app-search-slogan',
  standalone: true,
  imports: [ReactiveFormsModule, DatePipe],
  template: `
    <div class="space-y-6">
      <div class="border rounded-lg shadow-sm">
        <div class="p-6 border-b">
          <h2 class="text-xl font-semibold">Search Page Slogan Configuration</h2>
        </div>
        <div class="p-6">
          @if (isLoading()) {
            <div class="space-y-4"><div class="h-10 bg-gray-100 rounded animate-pulse"></div><div class="h-20 bg-gray-100 rounded animate-pulse"></div></div>
          } @else {
            <div class="space-y-6">
              @if (currentSlogan()) {
                <div class="bg-gradient-to-r from-blue-50 to-indigo-50 border border-blue-200 rounded-lg p-6">
                  <div class="text-center space-y-2">
                    <h2 class="text-2xl font-bold text-blue-900">{{ currentSlogan()!.primarySlogan }}</h2>
                    @if (currentSlogan()!.secondarySlogan) {
                      <p class="text-blue-700 text-lg">{{ currentSlogan()!.secondarySlogan }}</p>
                    }
                    <span class="inline-block px-3 py-1 rounded-full bg-blue-100 text-blue-800 text-xs font-medium mt-2">Current Active Slogan</span>
                  </div>
                </div>
              }
              <form [formGroup]="sloganForm" (ngSubmit)="onSubmit()" class="space-y-4">
                <div>
                  <label class="block text-sm font-medium mb-1">Primary Slogan</label>
                  <input type="text" formControlName="primarySlogan" placeholder="Enter primary slogan" maxlength="100" class="h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm" />
                  <div class="text-xs text-gray-500 mt-1">{{ sloganForm.get('primarySlogan')?.value?.length || 0 }}/100 characters</div>
                </div>
                <div>
                  <label class="block text-sm font-medium mb-1">Secondary Slogan (Optional)</label>
                  <textarea formControlName="secondarySlogan" rows="3" placeholder="Enter secondary slogan" maxlength="200" class="w-full rounded-md border border-input bg-background px-3 py-2 text-sm"></textarea>
                  <div class="text-xs text-gray-500 mt-1">{{ sloganForm.get('secondarySlogan')?.value?.length || 0 }}/200 characters</div>
                </div>
                <div class="flex justify-between items-center pt-4 border-t">
                  <span class="text-sm text-gray-500">{{ hasChanges() ? 'Unsaved changes' : '' }}</span>
                  <button type="submit" [disabled]="!hasChanges() || isSaving() || !sloganForm.get('primarySlogan')?.value?.trim()" class="h-10 bg-[#1a1a2e] text-white rounded-md px-6 font-medium disabled:opacity-50">
                    {{ isSaving() ? 'Saving...' : 'Save Changes' }}
                  </button>
                </div>
              </form>
              @if (currentSlogan()) {
                <div class="text-sm text-gray-500 border-t pt-4">
                  <div class="flex items-center justify-between">
                    <span>Last updated: {{ currentSlogan()!.lastUpdated | date:'medium' }}</span>
                    <span>Updated by: {{ currentSlogan()!.updatedBy }}</span>
                  </div>
                </div>
              }
            </div>
          }
        </div>
      </div>
    </div>
  `,
})
export class SearchSloganComponent implements OnInit {
  private api = inject(ApiService);
  private notification = inject(NotificationService);
  isLoading = signal(true);
  isSaving = signal(false);
  hasChanges = signal(false);
  currentSlogan = signal<any>(null);

  sloganForm = new FormGroup({
    primarySlogan: new FormControl('', [Validators.required]),
    secondarySlogan: new FormControl(''),
  });

  ngOnInit() {
    this.api.getSearchSlogan().subscribe({
      next: (data: any) => {
        this.currentSlogan.set(data);
        this.sloganForm.patchValue({
          primarySlogan: data.primarySlogan || '',
          secondarySlogan: data.secondarySlogan || '',
        });
        this.isLoading.set(false);
        this.hasChanges.set(false);
      },
      error: () => { this.isLoading.set(false); },
    });
    this.sloganForm.valueChanges.subscribe(() => this.hasChanges.set(true));
  }

  onSubmit() {
    if (this.sloganForm.invalid) return;
    this.isSaving.set(true);
    this.api.updateSearchSlogan(this.sloganForm.value).subscribe({
      next: () => {
        this.isSaving.set(false);
        this.hasChanges.set(false);
        this.notification.success('Search slogan updated successfully');
      },
      error: () => { this.isSaving.set(false); this.notification.error('Failed to update search slogan'); },
    });
  }
}
